// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlvuBPU1mZLiS9tW0Lh5H0N50xOM0d4y4',
    appId: '1:1002786344627:web:a30833e91c0cae1c596ac6',
    messagingSenderId: '1002786344627',
    projectId: 'market-connect-780fa',
    authDomain: 'market-connect-780fa.firebaseapp.com',
    storageBucket: 'market-connect-780fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyHHAG8hNsvee4y37041tEc6brp_nGyBw',
    appId: '1:1002786344627:android:f195b01e48384628596ac6',
    messagingSenderId: '1002786344627',
    projectId: 'market-connect-780fa',
    storageBucket: 'market-connect-780fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTCXAi4TI68R-hd_iyLCWHIpKCCFaweco',
    appId: '1:1002786344627:ios:9e987454a5add3b1596ac6',
    messagingSenderId: '1002786344627',
    projectId: 'market-connect-780fa',
    storageBucket: 'market-connect-780fa.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTCXAi4TI68R-hd_iyLCWHIpKCCFaweco',
    appId: '1:1002786344627:ios:9e987454a5add3b1596ac6',
    messagingSenderId: '1002786344627',
    projectId: 'market-connect-780fa',
    storageBucket: 'market-connect-780fa.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlvuBPU1mZLiS9tW0Lh5H0N50xOM0d4y4',
    appId: '1:1002786344627:web:1b0e35c78a741483596ac6',
    messagingSenderId: '1002786344627',
    projectId: 'market-connect-780fa',
    authDomain: 'market-connect-780fa.firebaseapp.com',
    storageBucket: 'market-connect-780fa.firebasestorage.app',
  );

}